### PR TITLE
Use configurable file paths for all libraries

### PR DESCRIPTION
**Pull request by valpackett**
and fix the readme and stuff.

### CODE REVIEW

**Comment by machty** [comment]
Thanks for putting this together. Does the code provide for a way to compile a non-emberized template? 

I see `@window.Emblem.precompile @window.Ember.Handlebars, data`, what would be nice is if you could detect if the filename had the pattern of `.raw.emblem`, which would trigger it to pass `@window.Handlebars` instead of Ember.Handlebars, which is how a raw Handlebars template is rendered. Should be pretty trivial since all the other hard parts are in place... would you mind putting that in there?

**Comment by machty** [comment]
Perhaps another idea would be if you don't provide an Ember path, all .emblem templates are assumed to be raw handlebars, rather than necessitating .raw.emblem to be in the name. I'd be happy w/ that, but you guys are more familiar with the brunch patterns than I

**Comment by valpackett** [comment]
I'll do this in my fork, good idea

**Comment by machty** [comment]
Could you update the test suite to test for both emberized and raw handlebars? Should be pretty trivial but we need that in there as a baseline.

**Comment by machty** [comment]
yo yo yo what's the status on all this?

**Comment by foxyblocks** [comment]
I think it should include default dependencies and use the path options as overrides. Less configuration for noobs.

**Comment by machty** [comment]
@myfreeweb is this ready to merge?

**Comment by valpackett** [comment]
yes

**Pull request merged**
